management:
  endpoints:
    web:
      exposure:
        include: health,info

info:
  project:
    name: KWATERA
    stage: empty-runtime-environment

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/database
    username: user
    password: secret123!

eureka:
  instance:
    prefer-ip-address: true