sonar.projectKey=kwatera-project_KWATERA_ocr-service
sonar.projectName=ocr-service

sonar.sources=app
sonar.tests=tests

sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8

sonar.exclusions=**/__pycache__/**,.venv/**
sonar.coverage.exclusions=tests/**