ALTER TABLE properties
    ADD COLUMN IF NOT EXISTS property_type VARCHAR(50);

ALTER TABLE units
    ADD COLUMN IF NOT EXISTS bedrooms INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS beds     INTEGER NOT NULL DEFAULT 0;
