import { useState } from "react";
import { format } from "date-fns";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { FileText, Download, Loader2 } from "lucide-react";
import { decodeJwt } from "../utils/jwtUtils";

interface ReservationMetrics {
  totalReservations: number;
  occupancyRate: number;
  occupiedDays: number;
}

interface BillingMetrics {
  revenueFromSettlements: number;
  unpaidBalance: number;
  paidSettlementsCount: number;
  unpaidSettlementsCount: number;
}

interface ReportExportButtonsProps {
  startDate: Date | null;
  endDate: Date | null;
  userRole: string;
  resMetrics: ReservationMetrics;
  billMetrics: BillingMetrics;
  totalUnitsCount: number;
}

export default function ReportExportButtons({
  startDate,
  endDate,
  userRole,
  resMetrics,
  billMetrics,
  totalUnitsCount,
}: ReportExportButtonsProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [statusMessage, setStatusMessage] = useState("");

  const totalReservations = resMetrics?.totalReservations ?? 0;
  const occupancyRate = resMetrics?.occupancyRate ?? 0;
  const occupiedDays = resMetrics?.occupiedDays ?? 0;

  const revenueFromSettlements = billMetrics?.revenueFromSettlements ?? 0;
  const unpaidBalance = billMetrics?.unpaidBalance ?? 0;
  const paidSettlementsCount = billMetrics?.paidSettlementsCount ?? 0;
  const unpaidSettlementsCount = billMetrics?.unpaidSettlementsCount ?? 0;

  const token = localStorage.getItem("token");
  const payload = token ? decodeJwt(token) : null;
  const sub = payload?.sub as string | undefined;
  const firstName = payload?.firstName as string | undefined;
  const lastName = payload?.lastName as string | undefined;
  const displayName =
    firstName && lastName
      ? `${firstName} ${lastName}`
      : sub
      ? sub.split("@")[0]
      : "User Profile";

  const formatDate = (date: Date | null) => {
    if (!date) return "N/A";
    return format(date, "yyyy-MM-dd");
  };

  const formatCurrency = (value: number) => {
    const rawString = value.toLocaleString("pl-PL", {
      minimumFractionDigits: 2,
      maximumFractionDigits: 2,
    });
    const cleanNumber = rawString.replace(/[\s\u00A0\u202F\u2007\u2008\u2009\u200A]/g, " ").trim();
    return `${cleanNumber} PLN`;
  };

  const handleDownloadCSV = () => {
    if (!startDate || !endDate) return;
    const startStr = formatDate(startDate);
    const endStr = formatDate(endDate);

    const csvRows = [
      ["KWATERA PROPERTY MANAGEMENT - SYSTEM REPORT"],
      [`Generated on: ${new Date().toLocaleString()}`],
      [`Period: ${startStr} to ${endStr}`],
      [`Role Scoping: ${userRole}`],
      [`Generated By: ${displayName}`],
      [],
      ["RESERVATION METRICS"],
      ["Metric", "Value"],
      ["Total Reservations", String(totalReservations)],
      ["Occupancy Rate", `${occupancyRate}%`],
      ["Occupied Days", String(occupiedDays)],
      ["Total Scoped Properties/Units", String(totalUnitsCount)],
      [],
      ["BILLING METRICS"],
      ["Metric", "Value (PLN)"],
      ["Total Collected Revenue", String(revenueFromSettlements)],
      ["Unpaid Receivables Balance", String(unpaidBalance)],
      ["Paid Invoices Count", String(paidSettlementsCount)],
      ["Unpaid Invoices Count", String(unpaidSettlementsCount)],
    ];

    const csvContent = csvRows
      .map((row) =>
        row.map((val) => (val.includes(",") ? `"${val}"` : val)).join(",")
      )
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `kwatera-${userRole.toLowerCase()}-report-${startStr}-to-${endStr}.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadPDF = async () => {
    if (!startDate || !endDate) return;
    setIsGenerating(true);
    setStatusMessage("Loading brand assets...");

    try {
      const logoEl = await new Promise<HTMLImageElement | null>((resolve) => {
        const img = new Image();
        img.src = "/kwatera.png";
        img.onload = () => resolve(img);
        img.onerror = () => {
          resolve(null);
        };
      });

      setStatusMessage("Capturing occupancy and revenue charts...");
      await new Promise((resolve) => setTimeout(resolve, 300));

      const occupancyChartEl = document.getElementById("occupancy-chart");
      let occupancyImg = "";
      let occupancyAspect = 1.6;
      if (occupancyChartEl) {
        const canvas = await html2canvas(occupancyChartEl, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
        });
        occupancyImg = canvas.toDataURL("image/png");
        occupancyAspect = occupancyChartEl.offsetWidth / occupancyChartEl.offsetHeight;
      }

      const revenueChartEl = document.getElementById("revenue-chart");
      let revenueImg = "";
      let revenueAspect = 1.6;
      if (revenueChartEl) {
        const canvas = await html2canvas(revenueChartEl, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
        });
        revenueImg = canvas.toDataURL("image/png");
        revenueAspect = revenueChartEl.offsetWidth / revenueChartEl.offsetHeight;
      }

      setStatusMessage("Generating report PDF...");

      const pdf = new jsPDF("p", "mm", "a4");

      if (logoEl) {
        pdf.addImage(logoEl, "PNG", 15, 14, 14, 14);
      }

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(22);
      pdf.setTextColor(66, 33, 29);
      pdf.text("KWATERA", logoEl ? 32 : 15, 21);

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(7.5);
      pdf.setTextColor(122, 122, 122);
      pdf.text("PROPERTY MANAGEMENT PLATFORM", logoEl ? 32 : 15, 26);

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(14);
      pdf.setTextColor(26, 26, 26);
      pdf.text("PERFORMANCE REPORT", 195, 21, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setFontSize(9);
      pdf.setTextColor(122, 122, 122);
      pdf.text("System-Generated Summary", 195, 26, { align: "right" });

      pdf.setDrawColor(66, 33, 29);
      pdf.setLineWidth(0.8);
      pdf.line(15, 32, 195, 32);

      pdf.setFillColor(253, 253, 253);
      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(15, 38, 180, 24, 3, 3, "FD");

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(66, 33, 29);
      pdf.text("Date Range:", 20, 46);
      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(26, 26, 26);
      pdf.text(`${formatDate(startDate)} to ${formatDate(endDate)}`, 52, 46);

      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(66, 33, 29);
      pdf.text("Monitored Units:", 20, 54);
      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(26, 26, 26);
      pdf.text(`${totalUnitsCount} units`, 52, 54);

      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(66, 33, 29);
      pdf.text("Generated By:", 110, 46);
      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(26, 26, 26);
      pdf.text(displayName, 138, 46);

      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(66, 33, 29);
      pdf.text("Access Role:", 110, 54);
      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(26, 26, 26);
      pdf.text(userRole === "ADMIN" ? "Global Administrator" : "Property Owner", 138, 54);

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(11);
      pdf.setTextColor(66, 33, 29);
      pdf.text("KEY PERFORMANCE INDICATORS (KPIS)", 15, 74);

      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.4);
      pdf.line(15, 77, 195, 77);

      pdf.setFillColor(66, 33, 29);
      pdf.rect(15, 82, 180, 10, "F");

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(255, 255, 255);
      pdf.text("Category", 20, 88.5);
      pdf.text("Metric Name", 65, 88.5);
      pdf.text("Value", 190, 88.5, { align: "right" });

      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);

      pdf.setFillColor(247, 247, 247);
      pdf.rect(15, 92, 45, 27, "F");
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(66, 33, 29);
      pdf.text("Reservations", 37.5, 107.5, { align: "center" });

      pdf.setFillColor(247, 247, 247);
      pdf.rect(15, 119, 45, 36, "F");
      pdf.text("Financials & Bills", 37.5, 139.5, { align: "center" });

      pdf.line(15, 92, 195, 92);
      pdf.line(15, 101, 195, 101);
      pdf.line(15, 110, 195, 110);
      pdf.line(15, 119, 195, 119);
      pdf.line(15, 128, 195, 128);
      pdf.line(15, 137, 195, 137);
      pdf.line(15, 146, 195, 146);
      pdf.line(15, 155, 195, 155);

      pdf.line(15, 82, 15, 155);
      pdf.line(60, 82, 60, 155);
      pdf.line(145, 82, 145, 155);
      pdf.line(195, 82, 195, 155);

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Total Booking Orders", 65, 97.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text(String(totalReservations), 190, 97.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Occupancy Rate", 65, 106.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(16, 185, 129);
      pdf.text(`${occupancyRate}%`, 190, 106.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Occupied Nights Total", 65, 115.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text(`${occupiedDays} nights`, 190, 115.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Collected Settlement Revenue", 65, 124.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(59, 130, 246);
      pdf.text(formatCurrency(revenueFromSettlements), 190, 124.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Outstanding Receivables Balance", 65, 133.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(245, 158, 11);
      pdf.text(formatCurrency(unpaidBalance), 190, 133.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Paid Settlements Count", 65, 142.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text(String(paidSettlementsCount), 190, 142.5, { align: "right" });

      pdf.setFont("Helvetica", "normal");
      pdf.setTextColor(85, 85, 85);
      pdf.text("Unpaid/Issued Invoices Count", 65, 151.5);
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text(String(unpaidSettlementsCount), 190, 151.5, { align: "right" });

      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);
      pdf.line(15, 280, 195, 280);

      pdf.setFont("Helvetica", "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(122, 122, 122);
      pdf.text(
        `Kwatera Property Management Report \u00a9 ${new Date().getFullYear()}`,
        15,
        286
      );
      pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 105, 286, {
        align: "center",
      });
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text("Page 1 of 2", 195, 286, { align: "right" });

      pdf.addPage();

      if (logoEl) {
        pdf.addImage(logoEl, "PNG", 15, 14, 10, 10);
      }

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(14);
      pdf.setTextColor(66, 33, 29);
      pdf.text("KWATERA", logoEl ? 28 : 15, 21);

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(9);
      pdf.setTextColor(122, 122, 122);
      pdf.text("CHART ANALYTICS & TRENDS", 195, 21, { align: "right" });

      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.4);
      pdf.line(15, 28, 195, 28);

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(11);
      pdf.setTextColor(66, 33, 29);
      pdf.text("Occupancy Trend Snapshot", 15, 36);

      pdf.setFillColor(255, 255, 255);
      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(15, 40, 180, 105, 3, 3, "FD");

      if (occupancyImg) {
        const cardW = 170;
        const cardH = 95;
        let w = cardW;
        let h = w / occupancyAspect;
        if (h > cardH) {
          h = cardH;
          w = h * occupancyAspect;
        }
        const x = 20 + (cardW - w) / 2;
        const y = 45 + (cardH - h) / 2;
        pdf.addImage(occupancyImg, "PNG", x, y, w, h);
      }

      pdf.setFont("Helvetica", "bold");
      pdf.setFontSize(11);
      pdf.setTextColor(66, 33, 29);
      pdf.text("Revenue & Media Expense Breakdown", 15, 156);

      pdf.setFillColor(255, 255, 255);
      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);
      pdf.roundedRect(15, 160, 180, 105, 3, 3, "FD");

      if (revenueImg) {
        const cardW = 170;
        const cardH = 95;
        let w = cardW;
        let h = w / revenueAspect;
        if (h > cardH) {
          h = cardH;
          w = h * revenueAspect;
        }
        const x = 20 + (cardW - w) / 2;
        const y = 165 + (cardH - h) / 2;
        pdf.addImage(revenueImg, "PNG", x, y, w, h);
      }

      pdf.setDrawColor(218, 205, 202);
      pdf.setLineWidth(0.3);
      pdf.line(15, 280, 195, 280);

      pdf.setFont("Helvetica", "normal");
      pdf.setFontSize(8);
      pdf.setTextColor(122, 122, 122);
      pdf.text(
        `Kwatera Property Management Report \u00a9 ${new Date().getFullYear()}`,
        15,
        286
      );
      pdf.text(`Generated on ${new Date().toLocaleDateString()}`, 105, 286, {
        align: "center",
      });
      pdf.setFont("Helvetica", "bold");
      pdf.setTextColor(26, 26, 26);
      pdf.text("Page 2 of 2", 195, 286, { align: "right" });

      const startStr = formatDate(startDate);
      const endStr = formatDate(endDate);
      pdf.save(
        `kwatera-${userRole.toLowerCase()}-report-${startStr}-to-${endStr}.pdf`
      );
    } catch (error) {
      console.error("Failed to generate PDF report:", error);
      alert("An error occurred while generating the PDF report. Please try again.");
    } finally {
      setIsGenerating(false);
      setStatusMessage("");
    }
  };

  return (
    <>
      <button
        type="button"
        onClick={handleDownloadCSV}
        className="px-4 py-2 text-sm font-bold text-[#42211D] bg-[#F7F7F7] border border-[#DACDCA] hover:bg-gray-100 rounded-lg transition-all shadow-sm cursor-pointer flex items-center gap-2 active:scale-[0.98]"
      >
        <FileText className="w-4 h-4" />
        Download CSV
      </button>

      <button
        type="button"
        disabled={isGenerating}
        onClick={handleDownloadPDF}
        className="px-5 py-2 text-sm font-bold text-white bg-[#42211D] hover:bg-[#341a17] rounded-lg transition-all shadow-md cursor-pointer flex items-center gap-2 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
      >
        {isGenerating ? (
          <Loader2 className="w-4 h-4 animate-spin" />
        ) : (
          <Download className="w-4 h-4" />
        )}
        Download Report (PDF)
      </button>

      {isGenerating && (
        <div className="fixed inset-0 bg-black/45 backdrop-blur-sm z-[9999] flex flex-col items-center justify-center text-white">
          <div className="bg-[#ffffff] text-[#1A1A1A] px-8 py-6 rounded-2xl shadow-2xl flex flex-col items-center gap-4 border border-[#DACDCA] max-w-sm text-center">
            <Loader2 className="w-8 h-8 text-[#42211D] animate-spin" />
            <h3 className="text-lg font-extrabold text-[#1A1A1A]">Generating Report</h3>
            <p className="text-sm text-[#7A7A7A] font-medium">{statusMessage}</p>
          </div>
        </div>
      )}
    </>
  );
}
