import { useState } from "react";
import { format } from "date-fns";
import { jsPDF } from "jspdf";
import html2canvas from "html2canvas";
import { FileText, Download, Loader2 } from "lucide-react";
import { decodeJwt } from "../utils/jwtUtils";

interface ReservationMetrics {
  totalReservations: number;
  occupancyRate: number;
  occupiedDays: number;
}

interface BillingMetrics {
  revenueFromSettlements: number;
  unpaidBalance: number;
  paidSettlementsCount: number;
  unpaidSettlementsCount: number;
}

interface ReportExportButtonsProps {
  startDate: Date | null;
  endDate: Date | null;
  userRole: string;
  resMetrics: ReservationMetrics;
  billMetrics: BillingMetrics;
  totalUnitsCount: number;
}

export default function ReportExportButtons({
  startDate,
  endDate,
  userRole,
  resMetrics,
  billMetrics,
  totalUnitsCount,
}: ReportExportButtonsProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [statusMessage, setStatusMessage] = useState("");
  const [occupancyImgSrc, setOccupancyImgSrc] = useState<string>("");
  const [revenueImgSrc, setRevenueImgSrc] = useState<string>("");

  const totalReservations = resMetrics?.totalReservations ?? 0;
  const occupancyRate = resMetrics?.occupancyRate ?? 0;
  const occupiedDays = resMetrics?.occupiedDays ?? 0;

  const revenueFromSettlements = billMetrics?.revenueFromSettlements ?? 0;
  const unpaidBalance = billMetrics?.unpaidBalance ?? 0;
  const paidSettlementsCount = billMetrics?.paidSettlementsCount ?? 0;
  const unpaidSettlementsCount = billMetrics?.unpaidSettlementsCount ?? 0;

  const token = localStorage.getItem("token");
  const payload = token ? decodeJwt(token) : null;
  const sub = payload?.sub as string | undefined;
  const firstName = payload?.firstName as string | undefined;
  const lastName = payload?.lastName as string | undefined;
  const displayName =
    firstName && lastName
      ? `${firstName} ${lastName}`
      : sub
      ? sub.split("@")[0]
      : "User Profile";

  const formatDate = (date: Date | null) => {
    if (!date) return "N/A";
    return format(date, "yyyy-MM-dd");
  };

  const handleDownloadCSV = () => {
    if (!startDate || !endDate) return;
    const startStr = formatDate(startDate);
    const endStr = formatDate(endDate);

    const csvRows = [
      ["KWATERA PROPERTY MANAGEMENT - SYSTEM REPORT"],
      [`Generated on: ${new Date().toLocaleString()}`],
      [`Period: ${startStr} to ${endStr}`],
      [`Role Scoping: ${userRole}`],
      [`Generated By: ${displayName}`],
      [],
      ["RESERVATION METRICS"],
      ["Metric", "Value"],
      ["Total Reservations", String(totalReservations)],
      ["Occupancy Rate", `${occupancyRate}%`],
      ["Occupied Days", String(occupiedDays)],
      ["Total Scoped Properties/Units", String(totalUnitsCount)],
      [],
      ["BILLING METRICS"],
      ["Metric", "Value (PLN)"],
      ["Total Collected Revenue", String(revenueFromSettlements)],
      ["Unpaid Receivables Balance", String(unpaidBalance)],
      ["Paid Invoices Count", String(paidSettlementsCount)],
      ["Unpaid Invoices Count", String(unpaidSettlementsCount)],
    ];

    const csvContent = csvRows
      .map((row) =>
        row.map((val) => (val.includes(",") ? `"${val}"` : val)).join(",")
      )
      .join("\n");

    const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.setAttribute("href", url);
    link.setAttribute(
      "download",
      `kwatera-${userRole.toLowerCase()}-report-${startStr}-to-${endStr}.csv`
    );
    link.style.visibility = "hidden";
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const handleDownloadPDF = async () => {
    if (!startDate || !endDate) return;
    setIsGenerating(true);
    setStatusMessage("Capturing occupancy and revenue charts...");

    try {
      await new Promise((resolve) => setTimeout(resolve, 300));

      const occupancyChartEl = document.getElementById("occupancy-chart");
      let occupancyImg = "";
      if (occupancyChartEl) {
        const canvas = await html2canvas(occupancyChartEl, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
        });
        occupancyImg = canvas.toDataURL("image/png");
      }

      const revenueChartEl = document.getElementById("revenue-chart");
      let revenueImg = "";
      if (revenueChartEl) {
        const canvas = await html2canvas(revenueChartEl, {
          scale: 2,
          useCORS: true,
          backgroundColor: "#ffffff",
          logging: false,
        });
        revenueImg = canvas.toDataURL("image/png");
      }

      setOccupancyImgSrc(occupancyImg);
      setRevenueImgSrc(revenueImg);
      setStatusMessage("Preparing print layout templates...");

      await new Promise((resolve) => setTimeout(resolve, 500));

      const page1El = document.getElementById("pdf-report-page-1");
      if (!page1El) throw new Error("Report page 1 element not found.");
      const page1Canvas = await html2canvas(page1El, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
      });
      const page1Img = page1Canvas.toDataURL("image/png");

      const page2El = document.getElementById("pdf-report-page-2");
      if (!page2El) throw new Error("Report page 2 element not found.");
      const page2Canvas = await html2canvas(page2El, {
        scale: 2,
        useCORS: true,
        backgroundColor: "#ffffff",
        logging: false,
      });
      const page2Img = page2Canvas.toDataURL("image/png");

      setStatusMessage("Generating final PDF file...");

      const pdf = new jsPDF("p", "mm", "a4");
      const imgWidth = 210;
      const imgHeight = 297;

      pdf.addImage(page1Img, "PNG", 0, 0, imgWidth, imgHeight);

      pdf.addPage();
      pdf.addImage(page2Img, "PNG", 0, 0, imgWidth, imgHeight);

      const startStr = formatDate(startDate);
      const endStr = formatDate(endDate);
      pdf.save(
        `kwatera-${userRole.toLowerCase()}-report-${startStr}-to-${endStr}.pdf`
      );
    } catch (error) {
      console.error("Failed to generate PDF report:", error);
      alert("An error occurred while generating the PDF report. Please try again.");
    } finally {
      setOccupancyImgSrc("");
      setRevenueImgSrc("");
      setIsGenerating(false);
      setStatusMessage("");
    }
  };

  return (
    <>
      <div className="flex flex-wrap items-center gap-3">
        <button
          type="button"
          onClick={handleDownloadCSV}
          className="px-4 py-2 text-sm font-bold text-[#42211D] bg-[#F7F7F7] border border-[#DACDCA] hover:bg-gray-100 rounded-lg transition-all shadow-sm cursor-pointer flex items-center gap-2 active:scale-[0.98]"
        >
          <FileText className="w-4 h-4" />
          Download CSV
        </button>

        <button
          type="button"
          disabled={isGenerating}
          onClick={handleDownloadPDF}
          className="px-5 py-2 text-sm font-bold text-white bg-[#42211D] hover:bg-[#341a17] rounded-lg transition-all shadow-md cursor-pointer flex items-center gap-2 active:scale-[0.98] disabled:opacity-50 disabled:cursor-not-allowed"
        >
          {isGenerating ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Download className="w-4 h-4" />
          )}
          Download Report (PDF)
        </button>
      </div>

      {isGenerating && (
        <div className="fixed inset-0 bg-black/45 backdrop-blur-sm z-[9999] flex flex-col items-center justify-center text-white">
          <div className="bg-[#ffffff] text-[#1A1A1A] px-8 py-6 rounded-2xl shadow-2xl flex flex-col items-center gap-4 border border-[#DACDCA] max-w-sm text-center">
            <Loader2 className="w-8 h-8 text-[#42211D] animate-spin" />
            <h3 className="text-lg font-extrabold text-[#1A1A1A]">Generating Report</h3>
            <p className="text-sm text-[#7A7A7A] font-medium">{statusMessage}</p>
          </div>
        </div>
      )}

      {isGenerating && (
        <div
          style={{
            position: "absolute",
            left: "-9999px",
            top: "-9999px",
            width: "800px",
            background: "#F7F7F7",
          }}
        >
          <div
            id="pdf-report-page-1"
            style={{
              width: "800px",
              height: "1130px",
              backgroundColor: "#ffffff",
              padding: "50px",
              boxSizing: "border-box",
              display: "flex",
              flexDirection: "column",
              fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
              color: "#1A1A1A",
              position: "relative",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                borderBottom: "3px solid #42211D",
                paddingBottom: "20px",
                marginBottom: "30px",
              }}
            >
              <div>
                <span
                  style={{
                    fontSize: "32px",
                    fontWeight: "900",
                    color: "#42211D",
                    letterSpacing: "0.15em",
                  }}
                >
                  KWATERA
                </span>
                <p style={{ margin: "4px 0 0 0", fontSize: "11px", color: "#7A7A7A", fontWeight: "bold", letterSpacing: "0.05em" }}>
                  PROPERTY MANAGEMENT PLATFORM
                </p>
              </div>
              <div style={{ textAlign: "right" }}>
                <span
                  style={{
                    fontSize: "18px",
                    fontWeight: "800",
                    color: "#1A1A1A",
                    letterSpacing: "0.05em",
                  }}
                >
                  PERFORMANCE REPORT
                </span>
                <p style={{ margin: "4px 0 0 0", fontSize: "11px", color: "#7A7A7A" }}>
                  System-Generated Summary
                </p>
              </div>
            </div>

            <div
              style={{
                backgroundColor: "#FDFDFD",
                border: "1px solid #DACDCA",
                borderRadius: "10px",
                padding: "20px",
                marginBottom: "40px",
                display: "grid",
                gridTemplateColumns: "1fr 1fr",
                gap: "20px",
                boxShadow: "0 2px 4px rgba(0,0,0,0.02)",
              }}
            >
              <div>
                <p style={{ margin: "6px 0", fontSize: "13px", color: "#7A7A7A" }}>
                  <strong style={{ color: "#42211D", fontSize: "12px", display: "inline-block", width: "120px" }}>Date Range:</strong>
                  <span style={{ color: "#1A1A1A", fontWeight: "700" }}>{formatDate(startDate)} to {formatDate(endDate)}</span>
                </p>
                <p style={{ margin: "6px 0", fontSize: "13px", color: "#7A7A7A" }}>
                  <strong style={{ color: "#42211D", fontSize: "12px", display: "inline-block", width: "120px" }}>Monitored Units:</strong>
                  <span style={{ color: "#1A1A1A", fontWeight: "700" }}>{totalUnitsCount} units</span>
                </p>
              </div>
              <div>
                <p style={{ margin: "6px 0", fontSize: "13px", color: "#7A7A7A" }}>
                  <strong style={{ color: "#42211D", fontSize: "12px", display: "inline-block", width: "120px" }}>Generated By:</strong>
                  <span style={{ color: "#1A1A1A", fontWeight: "700" }}>{displayName}</span>
                </p>
                <p style={{ margin: "6px 0", fontSize: "13px", color: "#7A7A7A" }}>
                  <strong style={{ color: "#42211D", fontSize: "12px", display: "inline-block", width: "120px" }}>Access Role:</strong>
                  <span style={{ color: "#1A1A1A", fontWeight: "700" }}>
                    {userRole === "ADMIN" ? "Global Administrator" : "Property Owner"}
                  </span>
                </p>
              </div>
            </div>

            <div style={{ flexGrow: 1 }}>
              <h3
                style={{
                  fontSize: "16px",
                  fontWeight: "800",
                  color: "#42211D",
                  borderBottom: "1.5px solid #DACDCA",
                  paddingBottom: "8px",
                  marginBottom: "15px",
                  textTransform: "uppercase",
                  letterSpacing: "0.05em",
                }}
              >
                Key Performance Indicators (KPIs)
              </h3>
              <table
                style={{
                  width: "100%",
                  borderCollapse: "collapse",
                  fontSize: "13px",
                  lineHeight: "1.5",
                }}
              >
                <thead>
                  <tr style={{ backgroundColor: "#42211D", color: "#ffffff" }}>
                    <th style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "left", fontWeight: "800" }}>Category</th>
                    <th style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "left", fontWeight: "800" }}>Metric Name</th>
                    <th style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "800", width: "180px" }}>Value</th>
                  </tr>
                </thead>
                <tbody>
                  <tr>
                    <td
                      rowSpan={3}
                      style={{
                        padding: "12px 16px",
                        border: "1px solid #DACDCA",
                        fontWeight: "800",
                        backgroundColor: "#F7F7F7",
                        color: "#42211D",
                        verticalAlign: "middle",
                      }}
                    >
                      Reservations
                    </td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Total Booking Orders</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "800", color: "#1A1A1A" }}>
                      {totalReservations}
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Occupancy Rate</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "800", color: "#10B981" }}>
                      {occupancyRate}%
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Occupied Nights Total</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "700", color: "#1A1A1A" }}>
                      {occupiedDays} nights
                    </td>
                  </tr>

                  <tr>
                    <td
                      rowSpan={4}
                      style={{
                        padding: "12px 16px",
                        border: "1px solid #DACDCA",
                        fontWeight: "800",
                        backgroundColor: "#F7F7F7",
                        color: "#42211D",
                        verticalAlign: "middle",
                      }}
                    >
                      Financials & Bills
                    </td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Collected Settlement Revenue</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "800", color: "#3B82F6" }}>
                      {revenueFromSettlements.toLocaleString("pl-PL", {
                        style: "currency",
                        currency: "PLN",
                      })}
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Outstanding Receivables Balance</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "800", color: "#F59E0B" }}>
                      {unpaidBalance.toLocaleString("pl-PL", {
                        style: "currency",
                        currency: "PLN",
                      })}
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Paid Settlements Count</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "700" }}>
                      {paidSettlementsCount}
                    </td>
                  </tr>
                  <tr>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", color: "#555" }}>Unpaid/Issued Invoices Count</td>
                    <td style={{ padding: "12px 16px", border: "1px solid #DACDCA", textAlign: "right", fontWeight: "700" }}>
                      {unpaidSettlementsCount}
                    </td>
                  </tr>
                </tbody>
              </table>
            </div>

            <div
              style={{
                borderTop: "1px solid #DACDCA",
                paddingTop: "15px",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                fontSize: "11px",
                color: "#7A7A7A",
              }}
            >
              <span>Kwatera Property Management Report &copy; {new Date().getFullYear()}</span>
              <span>Generated on {new Date().toLocaleDateString()}</span>
              <span style={{ fontWeight: "bold" }}>Page 1 of 2</span>
            </div>
          </div>

          <div
            id="pdf-report-page-2"
            style={{
              width: "800px",
              height: "1130px",
              backgroundColor: "#ffffff",
              padding: "50px",
              boxSizing: "border-box",
              display: "flex",
              flexDirection: "column",
              fontFamily: "system-ui, -apple-system, BlinkMacSystemFont, sans-serif",
              color: "#1A1A1A",
              position: "relative",
            }}
          >
            <div
              style={{
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                borderBottom: "1.5px solid #DACDCA",
                paddingBottom: "10px",
                marginBottom: "30px",
              }}
            >
              <span
                style={{
                  fontSize: "18px",
                  fontWeight: "900",
                  color: "#42211D",
                  letterSpacing: "0.15em",
                }}
              >
                KWATERA
              </span>
              <span style={{ fontSize: "11px", color: "#7A7A7A", fontWeight: "bold" }}>
                CHART ANALYTICS & TRENDS
              </span>
            </div>

            <div style={{ flexGrow: 1, display: "flex", flexDirection: "column", gap: "25px" }}>
              <div
                style={{
                  border: "1px solid #DACDCA",
                  borderRadius: "10px",
                  padding: "20px",
                  backgroundColor: "#ffffff",
                }}
              >
                <h4
                  style={{
                    fontSize: "14px",
                    fontWeight: "800",
                    color: "#42211D",
                    margin: "0 0 12px 0",
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                  }}
                >
                  Occupancy Trend Snapshot
                </h4>
                <div style={{ width: "100%", height: "300px", display: "flex", alignItems: "center", justifyContent: "center" }}>
                  {occupancyImgSrc ? (
                    <img
                      src={occupancyImgSrc}
                      alt="Occupancy Trend"
                      style={{ width: "100%", height: "100%", objectFit: "contain" }}
                    />
                  ) : (
                    <span style={{ fontSize: "12px", color: "#7A7A7A" }}>Rendering chart snapshot...</span>
                  )}
                </div>
              </div>

              <div
                style={{
                  border: "1px solid #DACDCA",
                  borderRadius: "10px",
                  padding: "20px",
                  backgroundColor: "#ffffff",
                }}
              >
                <h4
                  style={{
                    fontSize: "14px",
                    fontWeight: "800",
                    color: "#42211D",
                    margin: "0 0 12px 0",
                    textTransform: "uppercase",
                    letterSpacing: "0.05em",
                  }}
                >
                  Revenue & Media Expense Breakdown
                </h4>
                <div style={{ width: "100%", height: "300px", display: "flex", alignItems: "center", justifyContent: "center" }}>
                  {revenueImgSrc ? (
                    <img
                      src={revenueImgSrc}
                      alt="Revenue Flow Composed"
                      style={{ width: "100%", height: "100%", objectFit: "contain" }}
                    />
                  ) : (
                    <span style={{ fontSize: "12px", color: "#7A7A7A" }}>Rendering chart snapshot...</span>
                  )}
                </div>
              </div>
            </div>

            <div
              style={{
                borderTop: "1px solid #DACDCA",
                paddingTop: "15px",
                display: "flex",
                justifyContent: "space-between",
                alignItems: "center",
                fontSize: "11px",
                color: "#7A7A7A",
              }}
            >
              <span>Kwatera Property Management Report &copy; {new Date().getFullYear()}</span>
              <span>Generated on {new Date().toLocaleDateString()}</span>
              <span style={{ fontWeight: "bold" }}>Page 2 of 2</span>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
