import type { SystemEvent } from "../api/adminApi";

export const demoSystemEvents: SystemEvent[] = [
    {
        id: "demo-system-event-001",
        timestamp: "2026-07-08T11:18:00Z",
        actionType: "MEDIA_SETTLEMENT_GENERATED",
        actorUserId: "demo-user-admin",
        entityType: "SETTLEMENT",
        entityId: "demo-settlement-5014",
        details: "Generated utility settlement for demo-reservation-1014 after final meter readings were approved.",
    },
    {
        id: "demo-system-event-002",
        timestamp: "2026-07-08T11:10:00Z",
        actionType: "OCR_READING_SUCCEEDED",
        actorUserId: "demo-user-owner",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-5014",
        details: "Final water meter reading recognized as 151.7 with 93.8% confidence.",
    },
    {
        id: "demo-system-event-003",
        timestamp: "2026-07-04T16:20:00Z",
        actionType: "OCR_READING_ATTEMPTED",
        actorUserId: "demo-user-owner",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-5014",
        details: "Initial OCR meter reading attempted for Harbor Studio check-in.",
    },
    {
        id: "demo-system-event-004",
        timestamp: "2026-07-03T10:08:00Z",
        actionType: "PAYMENT_CANCELLED",
        actorUserId: "demo-user-guest-10",
        entityType: "RESERVATION",
        entityId: "demo-reservation-1013",
        details: "Payment authorization was cancelled after the reservation was cancelled.",
    },
    {
        id: "demo-system-event-005",
        timestamp: "2026-07-03T10:05:00Z",
        actionType: "RESERVATION_STATUS_CHANGED",
        actorUserId: "demo-user-admin",
        entityType: "RESERVATION",
        entityId: "demo-reservation-1013",
        details: "Reservation status changed from PENDING to CANCELLED for Market Square Suite.",
    },
    {
        id: "demo-system-event-006",
        timestamp: "2026-07-01T09:50:00Z",
        actionType: "RESERVATION_CREATED",
        actorUserId: "demo-user-guest-9",
        entityType: "RESERVATION",
        entityId: "demo-reservation-1012",
        details: "Guest reservation created for Trail Room from 2026-07-26 to 2026-07-29.",
    },
    {
        id: "demo-system-event-007",
        timestamp: "2026-06-30T07:30:00Z",
        actionType: "EXPIRED_RESERVATION_CANCELLED",
        actorUserId: null,
        entityType: "RESERVATION",
        entityId: "demo-reservation-expired-001",
        details: "Expired pending reservation was cancelled automatically after the payment window elapsed.",
    },
    {
        id: "demo-system-event-008",
        timestamp: "2026-06-29T18:25:00Z",
        actionType: "MANUAL_RESERVATION_CREATED",
        actorUserId: "demo-user-admin",
        entityType: "RESERVATION",
        entityId: "demo-reservation-1011",
        details: "Admin created a manual reservation for Lake Apartment on behalf of Alice Morgan.",
    },
    {
        id: "demo-system-event-009",
        timestamp: "2026-06-28T15:02:00Z",
        actionType: "PAYMENT_FAILED",
        actorUserId: "demo-user-guest-8",
        entityType: "RESERVATION",
        entityId: "demo-reservation-1010",
        details: "Demo payment failed for Executive Pier Suite reservation. No payment payload was stored.",
    },
    {
        id: "demo-system-event-010",
        timestamp: "2026-06-22T10:48:00Z",
        actionType: "METER_READING_MANUALLY_CORRECTED",
        actorUserId: "demo-user-admin",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-5006",
        details: "Final water reading corrected from 141.2 to 141.0 after manual review.",
    },
    {
        id: "demo-system-event-011",
        timestamp: "2026-06-22T10:40:00Z",
        actionType: "OCR_READING_FAILED",
        actorUserId: "demo-user-owner",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-5006",
        details: "Final water meter reading required manual review because confidence was below the approval threshold.",
    },
    {
        id: "demo-system-event-012",
        timestamp: "2026-06-18T08:00:00Z",
        actionType: "UNIT_BLOCKED",
        actorUserId: "demo-user-admin",
        entityType: "UNIT",
        entityId: "demo-unit-sopot-a",
        details: "Harbor Studio was blocked for maintenance between 2026-06-23 and 2026-06-24.",
    },
    {
        id: "demo-system-event-013",
        timestamp: "2026-06-09T12:45:00Z",
        actionType: "BALANCE_CHANGED",
        actorUserId: "demo-user-admin",
        entityType: "USER_BALANCE",
        entityId: "demo-user-guest-6",
        details: "Guest balance changed by 2240 PLN after Lake Apartment reservation confirmation.",
    },
];
