import type { Property, Unit } from "../types/property";

export const demoProperties: Property[] = [
    {
        id: "demo-property-forest-retreat",
        title: "Forest Retreat",
        description: "A cozy cabin surrounded by the forests of the Zywiec Beskids, perfect for a peaceful getaway and outdoor adventures.",
        city: "Szczyrk",
        country: "Poland",
        postalCode: "43-370",
        street: "Lesna",
        streetNumber: "12",
        latitude: 49.7177,
        longitude: 19.032,
        imageUrl: "https://images.pexels.com/photos/18628485/pexels-photo-18628485.jpeg",
        propertyType: "Cabin",
        amenities: ["WiFi", "Parking", "Fireplace", "BBQ"],
    },
    {
        id: "demo-property-mountain-escape",
        title: "Mountain Escape",
        description: "A charming mountain cabin offering breathtaking views of the Tatra Mountains and easy access to hiking trails.",
        city: "Koscielisko",
        country: "Poland",
        postalCode: "34-511",
        street: "Nedzy Kubinca",
        streetNumber: "45",
        latitude: 49.2902,
        longitude: 19.8895,
        imageUrl: "https://images.pexels.com/photos/13181168/pexels-photo-13181168.jpeg",
        propertyType: "Cabin",
        amenities: ["WiFi", "Hot Tub", "Parking", "Fireplace"],
    },
    {
        id: "demo-property-evergreen-cabin",
        title: "Evergreen Cabin",
        description: "A traditional wooden cabin surrounded by evergreen forests, offering peace, privacy, and an authentic mountain atmosphere.",
        city: "Wetlina",
        country: "Poland",
        postalCode: "38-608",
        street: "Bieszczadzka",
        streetNumber: "7",
        latitude: 49.1279,
        longitude: 22.468,
        imageUrl: "https://images.pexels.com/photos/35124483/pexels-photo-35124483.jpeg",
        propertyType: "Cabin",
        amenities: ["WiFi", "BBQ", "Terrace", "Parking"],
    },
    {
        id: "demo-property-spruce-hideaway",
        title: "Spruce Hideaway",
        description: "A comfortable cabin located near the Karkonosze Mountains, ideal for families and nature lovers.",
        city: "Karpacz",
        country: "Poland",
        postalCode: "58-540",
        street: "Lesna",
        streetNumber: "18",
        latitude: 50.7767,
        longitude: 15.755,
        imageUrl: "https://images.pexels.com/photos/8001411/pexels-photo-8001411.jpeg",
        propertyType: "Cabin",
        amenities: ["WiFi", "Sauna", "Parking", "Fireplace"],
    },
    {
        id: "demo-property-masurian-forest-lodge",
        title: "Masurian Forest Lodge",
        description: "A lakeside cabin surrounded by the beautiful forests of Masuria, offering relaxation and water activities.",
        city: "Mikolajki",
        country: "Poland",
        postalCode: "11-730",
        street: "Jeziorna",
        streetNumber: "4",
        latitude: 53.8023,
        longitude: 21.5701,
        imageUrl: "https://images.pexels.com/photos/17804250/pexels-photo-17804250.jpeg",
        propertyType: "Cottage",
        amenities: ["WiFi", "Kayaks", "Parking", "BBQ"],
    },
    {
        id: "demo-property-gdansk-city-apartment",
        title: "Gdansk City Apartment",
        description: "A modern apartment located close to Gdansk Old Town, featuring stylish interiors and excellent city access.",
        city: "Gdansk",
        country: "Poland",
        postalCode: "80-830",
        street: "Dluga",
        streetNumber: "15",
        latitude: 54.348,
        longitude: 18.653,
        imageUrl: "https://images.pexels.com/photos/34360421/pexels-photo-34360421.jpeg",
        propertyType: "Apartment",
        amenities: ["WiFi", "Elevator", "Air Conditioning"],
    },
    {
        id: "demo-property-krakow-old-town-apartment",
        title: "Krakow Old Town Apartment",
        description: "A stylish apartment in the heart of Krakow, within walking distance of historic landmarks and restaurants.",
        city: "Krakow",
        country: "Poland",
        postalCode: "31-017",
        street: "Florianska",
        streetNumber: "22",
        latitude: 50.0647,
        longitude: 19.945,
        imageUrl: "https://images.pexels.com/photos/31656149/pexels-photo-31656149.jpeg",
        propertyType: "Apartment",
        amenities: ["WiFi", "Air Conditioning", "Balcony"],
    },
    {
        id: "demo-property-riverside-apartment",
        title: "Riverside Apartment",
        description: "A comfortable apartment overlooking the Odra River, offering modern amenities and a central location.",
        city: "Wroclaw",
        country: "Poland",
        postalCode: "50-001",
        street: "Kotlarska",
        streetNumber: "8",
        latitude: 51.1079,
        longitude: 17.0385,
        imageUrl: "https://images.pexels.com/photos/34360419/pexels-photo-34360419.jpeg",
        propertyType: "Apartment",
        amenities: ["WiFi", "Parking", "Elevator"],
    },
    {
        id: "demo-property-seaside-apartment",
        title: "Seaside Apartment",
        description: "A bright and spacious apartment located near the beach, perfect for a relaxing seaside vacation.",
        city: "Sopot",
        country: "Poland",
        postalCode: "81-701",
        street: "Bohaterow Monte Cassino",
        streetNumber: "33",
        latitude: 54.4418,
        longitude: 18.56,
        imageUrl: "https://images.pexels.com/photos/27075286/pexels-photo-27075286.jpeg",
        propertyType: "Apartment",
        amenities: ["WiFi", "Parking", "Elevator"],
    },
    {
        id: "demo-property-business-class-apartment",
        title: "Business Class Apartment",
        description: "An elegant apartment designed for business travelers, offering premium comfort in the center of Warsaw.",
        city: "Warszawa",
        country: "Poland",
        postalCode: "00-001",
        street: "Marszalkowska",
        streetNumber: "100",
        latitude: 52.2297,
        longitude: 21.0122,
        imageUrl: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
        propertyType: "Apartment",
        amenities: ["WiFi", "Air Conditioning", "Gym", "Elevator"],
    },
];

export const demoUnitsByProperty: Record<string, Unit[]> = {
    "demo-property-forest-retreat": [
        {
            id: "demo-unit-entire-forest-cabin",
            propertyId: "demo-property-forest-retreat",
            name: "Entire Forest Cabin",
            description: "A private forest cabin with a fireplace and outdoor barbecue area.",
            pricePerNight: 420,
            capacity: 6,
            imageUrl: "https://images.pexels.com/photos/7746099/pexels-photo-7746099.jpeg",
            unitType: "ENTIRE_COTTAGE",
            unitNumber: "FR-1",
            floor: 0,
            amenities: ["WiFi", "Fireplace", "BBQ", "Parking"],
            bedrooms: 3,
            beds: 4,
        },
    ],
    "demo-property-mountain-escape": [
        {
            id: "demo-unit-entire-mountain-cabin",
            propertyId: "demo-property-mountain-escape",
            name: "Entire Mountain Cabin",
            description: "A spacious mountain cabin with panoramic views of the Tatra Mountains.",
            pricePerNight: 550,
            capacity: 8,
            imageUrl: "https://images.pexels.com/photos/7746949/pexels-photo-7746949.jpeg",
            unitType: "ENTIRE_COTTAGE",
            unitNumber: "ME-1",
            floor: 0,
            amenities: ["WiFi", "Hot Tub", "Fireplace", "Parking"],
            bedrooms: 4,
            beds: 5,
        },
    ],
    "demo-property-evergreen-cabin": [
        {
            id: "demo-unit-entire-nature-cabin",
            propertyId: "demo-property-evergreen-cabin",
            name: "Entire Nature Cabin",
            description: "A cozy private attic room in a wooden cabin surrounded by nature.",
            pricePerNight: 600,
            capacity: 8,
            imageUrl: "https://images.pexels.com/photos/7746476/pexels-photo-7746476.jpeg",
            unitType: "ENTIRE_COTTAGE",
            unitNumber: "AT-1",
            floor: 1,
            amenities: ["WiFi", "Shared Kitchen", "Parking"],
            bedrooms: 3,
            beds: 5,
        },
    ],
    "demo-property-spruce-hideaway": [
        {
            id: "demo-unit-attic-room",
            propertyId: "demo-property-spruce-hideaway",
            name: "Attic Room",
            description: "A cozy private attic room in a wooden cabin surrounded by nature.",
            pricePerNight: 180,
            capacity: 2,
            imageUrl: "https://images.pexels.com/photos/7745977/pexels-photo-7745977.jpeg",
            unitType: "PRIVATE_ROOM_IN_HOME",
            unitNumber: "SH-1",
            floor: 0,
            amenities: ["WiFi", "Sauna", "Fireplace", "Parking"],
            bedrooms: 1,
            beds: 1,
        },
    ],
    "demo-property-masurian-forest-lodge": [
        {
            id: "demo-unit-entire-lakeside-cottage",
            propertyId: "demo-property-masurian-forest-lodge",
            name: "Entire Lakeside Cottage",
            description: "A charming lakeside cottage with direct access to outdoor recreation.",
            pricePerNight: 480,
            capacity: 6,
            imageUrl: "https://images.pexels.com/photos/6296918/pexels-photo-6296918.jpeg",
            unitType: "ENTIRE_COTTAGE",
            unitNumber: "MF-1",
            floor: 0,
            amenities: ["WiFi", "Kayaks", "BBQ", "Parking"],
            bedrooms: 3,
            beds: 4,
        },
    ],
    "demo-property-gdansk-city-apartment": [
        {
            id: "demo-unit-city-center-apartment",
            propertyId: "demo-property-gdansk-city-apartment",
            name: "City Center Apartment",
            description: "Modern apartment located in the heart of Gdansk Old Town.",
            pricePerNight: 350,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6899438/pexels-photo-6899438.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A101",
            floor: 1,
            amenities: ["WiFi", "Air Conditioning", "Elevator"],
            bedrooms: 2,
            beds: 2,
        },
        {
            id: "demo-unit-premium-city-apartment",
            propertyId: "demo-property-gdansk-city-apartment",
            name: "Premium City Apartment",
            description: "A stylish and fully equipped premium apartment in Gdansk, ideal for longer stays and business travelers.",
            pricePerNight: 420,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6899439/pexels-photo-6899439.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A102",
            floor: 1,
            amenities: ["WiFi", "Air Conditioning", "Elevator"],
            bedrooms: 2,
            beds: 2,
        },
    ],
    "demo-property-krakow-old-town-apartment": [
        {
            id: "demo-unit-historic-center-apartment",
            propertyId: "demo-property-krakow-old-town-apartment",
            name: "Historic Center Apartment",
            description: "Elegant apartment within walking distance of Krakow's main attractions.",
            pricePerNight: 380,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6492403/pexels-photo-6492403.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A202",
            floor: 2,
            amenities: ["WiFi", "Balcony", "Air Conditioning"],
            bedrooms: 2,
            beds: 2,
        },
        {
            id: "demo-unit-old-town-comfort-apartment",
            propertyId: "demo-property-krakow-old-town-apartment",
            name: "Old Town Comfort Apartment",
            description: "Comfortable apartment located in historic Krakow Old Town with upgraded amenities.",
            pricePerNight: 430,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6492396/pexels-photo-6492396.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "K301",
            floor: 3,
            amenities: ["WiFi", "Balcony", "Air Conditioning", "Historic View"],
            bedrooms: 2,
            beds: 2,
        },
    ],
    "demo-property-riverside-apartment": [
        {
            id: "demo-unit-odra-view-apartment",
            propertyId: "demo-property-riverside-apartment",
            name: "Odra View Apartment",
            description: "Comfortable apartment with views of the Odra River.",
            pricePerNight: 340,
            capacity: 3,
            imageUrl: "https://images.pexels.com/photos/7018401/pexels-photo-7018401.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A303",
            floor: 3,
            amenities: ["WiFi", "Elevator", "Parking"],
            bedrooms: 1,
            beds: 2,
        },
        {
            id: "demo-unit-riverside-deluxe-apartment",
            propertyId: "demo-property-riverside-apartment",
            name: "Riverside Deluxe Apartment",
            description: "Modern riverside apartment with enhanced comfort and upgraded interior design.",
            pricePerNight: 390,
            capacity: 3,
            imageUrl: "https://images.pexels.com/photos/7018387/pexels-photo-7018387.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "R201",
            floor: 2,
            amenities: ["WiFi", "Elevator", "Parking", "River View"],
            bedrooms: 1,
            beds: 2,
        },
    ],
    "demo-property-seaside-apartment": [
        {
            id: "demo-unit-beachside-apartment",
            propertyId: "demo-property-seaside-apartment",
            name: "Beachside Apartment",
            description: "Bright apartment located just minutes from the beach.",
            pricePerNight: 450,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6585598/pexels-photo-6585598.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A404",
            floor: 4,
            amenities: ["WiFi", "Balcony", "Parking"],
            bedrooms: 2,
            beds: 2,
        },
        {
            id: "demo-unit-seaside-luxury-apartment",
            propertyId: "demo-property-seaside-apartment",
            name: "Seaside Luxury Apartment",
            description: "Luxury seaside apartment with panoramic coastal views and modern interior.",
            pricePerNight: 520,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/6585601/pexels-photo-6585601.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "S501",
            floor: 5,
            amenities: ["WiFi", "Balcony", "Parking", "Sea View"],
            bedrooms: 2,
            beds: 2,
        },
    ],
    "demo-property-business-class-apartment": [
        {
            id: "demo-unit-executive-apartment",
            propertyId: "demo-property-business-class-apartment",
            name: "Executive Apartment",
            description: "Premium apartment designed for business travelers in central Warsaw.",
            pricePerNight: 520,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "A505",
            floor: 5,
            amenities: ["WiFi", "Air Conditioning", "Gym", "Elevator"],
            bedrooms: 2,
            beds: 2,
        },
        {
            id: "demo-unit-executive-plus-apartment",
            propertyId: "demo-property-business-class-apartment",
            name: "Executive Plus Apartment",
            description: "High-end executive apartment with extra workspace and premium amenities.",
            pricePerNight: 590,
            capacity: 4,
            imageUrl: "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
            unitType: "ENTIRE_APARTMENT",
            unitNumber: "B601",
            floor: 6,
            amenities: ["WiFi", "Air Conditioning", "Gym", "Elevator"],
            bedrooms: 2,
            beds: 2,
        },
    ],
};

export const demoPropertyImages: Record<string, string[]> = {
    "demo-property-forest-retreat": [
        "https://images.pexels.com/photos/18628485/pexels-photo-18628485.jpeg",
        "https://images.pexels.com/photos/7746099/pexels-photo-7746099.jpeg",
        "https://images.pexels.com/photos/7746103/pexels-photo-7746103.jpeg",
    ],
    "demo-property-mountain-escape": [
        "https://images.pexels.com/photos/13181168/pexels-photo-13181168.jpeg",
        "https://images.pexels.com/photos/7746949/pexels-photo-7746949.jpeg",
        "https://images.pexels.com/photos/7746941/pexels-photo-7746941.jpeg",
    ],
    "demo-property-evergreen-cabin": [
        "https://images.pexels.com/photos/35124483/pexels-photo-35124483.jpeg",
        "https://images.pexels.com/photos/7746476/pexels-photo-7746476.jpeg",
        "https://images.pexels.com/photos/7746470/pexels-photo-7746470.jpeg",
    ],
    "demo-property-spruce-hideaway": [
        "https://images.pexels.com/photos/8001411/pexels-photo-8001411.jpeg",
        "https://images.pexels.com/photos/7745977/pexels-photo-7745977.jpeg",
        "https://images.pexels.com/photos/7745978/pexels-photo-7745978.jpeg",
    ],
    "demo-property-masurian-forest-lodge": [
        "https://images.pexels.com/photos/17804250/pexels-photo-17804250.jpeg",
        "https://images.pexels.com/photos/6296918/pexels-photo-6296918.jpeg",
        "https://images.pexels.com/photos/6296919/pexels-photo-6296919.jpeg",
    ],
    "demo-property-gdansk-city-apartment": [
        "https://images.pexels.com/photos/34360421/pexels-photo-34360421.jpeg",
        "https://images.pexels.com/photos/6899438/pexels-photo-6899438.jpeg",
        "https://images.pexels.com/photos/6899439/pexels-photo-6899439.jpeg",
    ],
    "demo-property-krakow-old-town-apartment": [
        "https://images.pexels.com/photos/31656149/pexels-photo-31656149.jpeg",
        "https://images.pexels.com/photos/31656153/pexels-photo-31656153.jpeg",
        "https://images.pexels.com/photos/6492403/pexels-photo-6492403.jpeg",
    ],
    "demo-property-riverside-apartment": [
        "https://images.pexels.com/photos/34360419/pexels-photo-34360419.jpeg",
        "https://images.pexels.com/photos/7018401/pexels-photo-7018401.jpeg",
        "https://images.pexels.com/photos/7018387/pexels-photo-7018387.jpeg",
    ],
    "demo-property-seaside-apartment": [
        "https://images.pexels.com/photos/27075286/pexels-photo-27075286.jpeg",
        "https://images.pexels.com/photos/6585598/pexels-photo-6585598.jpeg",
        "https://images.pexels.com/photos/6585601/pexels-photo-6585601.jpeg",
    ],
    "demo-property-business-class-apartment": [
        "https://images.pexels.com/photos/439391/pexels-photo-439391.jpeg",
        "https://images.pexels.com/photos/439227/pexels-photo-439227.jpeg",
    ],
};

export const demoOccupiedDatesByUnit: Record<string, { startDate: string; endDate: string }[]> = {
    "demo-unit-entire-forest-cabin": [
        { startDate: "2026-01-18", endDate: "2026-01-22" },
        { startDate: "2026-06-15", endDate: "2026-06-21" },
    ],
    "demo-unit-entire-mountain-cabin": [
        { startDate: "2026-02-17", endDate: "2026-02-24" },
        { startDate: "2026-07-07", endDate: "2026-07-14" },
    ],
    "demo-unit-entire-nature-cabin": [
        { startDate: "2026-03-19", endDate: "2026-03-22" },
        { startDate: "2026-08-01", endDate: "2026-08-05" },
    ],
    "demo-unit-attic-room": [
        { startDate: "2026-04-18", endDate: "2026-04-20" },
    ],
    "demo-unit-entire-lakeside-cottage": [
        { startDate: "2026-05-03", endDate: "2026-05-08" },
        { startDate: "2026-08-16", endDate: "2026-08-19" },
    ],
    "demo-unit-city-center-apartment": [
        { startDate: "2026-05-18", endDate: "2026-05-22" },
        { startDate: "2026-09-15", endDate: "2026-09-17" },
    ],
    "demo-unit-premium-city-apartment": [
        { startDate: "2026-11-14", endDate: "2026-11-17" },
    ],
    "demo-unit-historic-center-apartment": [
        { startDate: "2026-05-28", endDate: "2026-05-31" },
        { startDate: "2026-10-15", endDate: "2026-10-21" },
    ],
    "demo-unit-old-town-comfort-apartment": [
        { startDate: "2026-06-27", endDate: "2026-07-02" },
    ],
    "demo-unit-odra-view-apartment": [
        { startDate: "2026-06-07", endDate: "2026-06-09" },
        { startDate: "2026-07-17", endDate: "2026-07-19" },
    ],
    "demo-unit-riverside-deluxe-apartment": [],
    "demo-unit-beachside-apartment": [
        { startDate: "2026-08-31", endDate: "2026-09-04" },
    ],
    "demo-unit-seaside-luxury-apartment": [
        { startDate: "2026-06-16", endDate: "2026-06-20" },
    ],
    "demo-unit-executive-apartment": [],
    "demo-unit-executive-plus-apartment": [
        { startDate: "2026-06-22", endDate: "2026-06-25" },
    ],
};

export function getDemoUnits(propertyId: string, currency = "PLN") {
    const units = demoUnitsByProperty[propertyId] ?? [];
    if (currency === "PLN") return units;

    const rates: Record<string, number> = { EUR: 4.35, USD: 3.95 };
    const rate = rates[currency] ?? 1;

    return units.map((unit) => ({
        ...unit,
        convertedPricePerNight: Number((unit.pricePerNight / rate).toFixed(2)),
        currencyInfo: {
            baseCurrency: "PLN",
            displayCurrency: currency,
            exchangeRate: rate,
            rateEffectiveDate: "2026-06-17",
        },
    }));
}
