import type { SystemEvent } from "../api/adminApi";

export const demoSystemEvents: SystemEvent[] = [
    {
        id: "demo-system-event-001",
        timestamp: "2026-06-17T11:58:00Z",
        actionType: "RESERVATION_CREATED",
        actorUserId: "demo-user-guest-10",
        entityType: "RESERVATION",
        entityId: "demo-reservation-0024",
        details: "Fresh pending reservation created for Beachside Apartment from 2026-08-31 to 2026-09-04.",
    },
    {
        id: "demo-system-event-002",
        timestamp: "2026-06-17T11:55:00Z",
        actionType: "RESERVATION_CREATED",
        actorUserId: "demo-user-guest-9",
        entityType: "RESERVATION",
        entityId: "demo-reservation-0023",
        details: "Fresh pending reservation created for Odra View Apartment from 2026-07-17 to 2026-07-19.",
    },
    {
        id: "demo-system-event-003",
        timestamp: "2026-06-17T16:55:00Z",
        actionType: "RESERVATION_STATUS_CHANGED",
        actorUserId: "demo-user-owner",
        entityType: "RESERVATION",
        entityId: "demo-reservation-0015",
        details: "Reservation moved from PENDING to CONFIRMED for Executive Plus Apartment.",
    },
    {
        id: "demo-system-event-004",
        timestamp: "2026-06-09T11:00:00Z",
        actionType: "MEDIA_SETTLEMENT_GENERATED",
        actorUserId: "demo-user-admin",
        entityType: "SETTLEMENT",
        entityId: "demo-settlement-0008",
        details: "Generated water settlement for Odra View Apartment after final meter reading approval.",
    },
    {
        id: "demo-system-event-005",
        timestamp: "2026-06-09T11:00:00Z",
        actionType: "OCR_READING_SUCCEEDED",
        actorUserId: "demo-user-owner",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-0008",
        details: "Final water meter reading recognized as 90.583 with 74.2% confidence.",
    },
    {
        id: "demo-system-event-006",
        timestamp: "2026-06-04T12:00:00Z",
        actionType: "RESERVATION_STATUS_CHANGED",
        actorUserId: "demo-user-guest-6",
        entityType: "RESERVATION",
        entityId: "demo-reservation-0012",
        details: "Confirmed Riverside Deluxe Apartment reservation was cancelled before check-in.",
    },
    {
        id: "demo-system-event-007",
        timestamp: "2026-05-31T11:00:00Z",
        actionType: "BALANCE_CHANGED",
        actorUserId: "demo-user-guest-9",
        entityType: "SETTLEMENT",
        entityId: "demo-settlement-0007",
        details: "Paid completed-stay settlement for Historic Center Apartment.",
    },
    {
        id: "demo-system-event-008",
        timestamp: "2026-05-28T14:45:00Z",
        actionType: "EXPIRED_RESERVATION_CANCELLED",
        actorUserId: null,
        entityType: "RESERVATION",
        entityId: "demo-reservation-0025",
        details: "Future pending reservation for Executive Apartment expired after the payment window elapsed.",
    },
    {
        id: "demo-system-event-009",
        timestamp: "2026-05-22T11:00:00Z",
        actionType: "OCR_READING_SUCCEEDED",
        actorUserId: "demo-user-owner",
        entityType: "MEDIA_READING",
        entityId: "demo-reading-water-0006",
        details: "Final water meter reading recognized for City Center Apartment.",
    },
    {
        id: "demo-system-event-010",
        timestamp: "2026-05-10T14:45:00Z",
        actionType: "EXPIRED_RESERVATION_CANCELLED",
        actorUserId: null,
        entityType: "RESERVATION",
        entityId: "demo-reservation-0010",
        details: "Premium City Apartment reservation was automatically cancelled after pending payment expired.",
    },
    {
        id: "demo-system-event-011",
        timestamp: "2026-05-08T11:00:00Z",
        actionType: "BALANCE_CHANGED",
        actorUserId: "demo-user-guest-7",
        entityType: "SETTLEMENT",
        entityId: "demo-settlement-0005",
        details: "Paid completed-stay settlement for Entire Lakeside Cottage, including water usage.",
    },
    {
        id: "demo-system-event-012",
        timestamp: "2026-04-20T11:00:00Z",
        actionType: "MEDIA_SETTLEMENT_GENERATED",
        actorUserId: "demo-user-admin",
        entityType: "SETTLEMENT",
        entityId: "demo-settlement-0004",
        details: "Generated water settlement for Attic Room after check-out meter reading.",
    },
];
