services:
  config-server:
    build:
      context: ../../services/config-server
    container_name: kwatera-config-server
    ports:
      - "8888:8888"
    volumes:
      - ../../config-repo:/config-repo:ro

  service-registry:
    build:
      context: ../../services/service-registry
    container_name: kwatera-service-registry
    ports:
      - "8761:8761"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
    depends_on:
      - config-server

  reservation-service:
    build:
      context: ../../services/reservation-service
    container_name: kwatera-reservation-service
    ports:
      - "8080:8080"
    environment:
      CONFIG_SERVER_URL: http://config-server:8888
      EUREKA_DEFAULT_ZONE: http://service-registry:8761/eureka
    depends_on:
      - config-server
      - service-registry