server:
  port: 8090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**

        - id: reservation-service-admin
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/admin/reservations/**

        - id: reservation-service-availability
          uri: lb://reservation-service
          predicates:
            - Path=/api/availability/**

        - id: property-service
          uri: lb://property-service
          predicates:
            - Path=/api/properties/**

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
