server:
  port: 8090

spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://config-server:8888
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin RETAIN_FIRST
          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth,/api/auth/**

            - id: auth-service-admin
              uri: lb://auth-service
              predicates:
                - Path=/api/admin/users,/api/admin/users/**

            - id: reservation-service
              uri: lb://reservation-service
              predicates:
                - Path=/api/v1/reservations,/api/v1/reservations/**

            - id: reservation-service-admin
              uri: lb://reservation-service
              predicates:
                - Path=/api/v1/admin/reservations,/api/v1/admin/reservations/**,/api/v1/admin/occupancy,/api/v1/admin/occupancy/**,/api/v1/admin/dashboard/reservations,/api/v1/admin/dashboard/reservations/**,/api/v1/admin/system-events,/api/v1/admin/system-events/**

            - id: reservation-service-availability
              uri: lb://reservation-service
              predicates:
                - Path=/api/availability,/api/availability/**

            - id: property-service
              uri: lb://property-service
              predicates:
                - Path=/api/properties,/api/properties/**

            - id: property-service-owner
              uri: lb://property-service
              predicates:
                - Path=/api/owner/**

            - id: billing-service
              uri: lb://billing-service
              predicates:
                - Path=/api/billing/**

            - id: billing-service-admin
              uri: lb://billing-service
              predicates:
                - Path=/api/v1/admin/dashboard/billing,/api/v1/admin/dashboard/billing/**

            - id: ai-pricing-service
              uri: lb://ai-pricing-service
              predicates:
                - Path=/api/predict/**


eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info
