package io.github.kwatera_project.kwatera.reservation_service.audit;

public enum SystemEventType {
  RESERVATION_CREATED,
  MANUAL_RESERVATION_CREATED,
  UNIT_BLOCKED,
  RESERVATION_STATUS_CHANGED,
  EXPIRED_RESERVATION_CANCELLED,
  OCR_READING_ATTEMPTED,
  OCR_READING_SUCCEEDED,
  OCR_READING_FAILED,
  METER_READING_MANUALLY_CORRECTED,
  MEDIA_SETTLEMENT_GENERATED,
  PAYMENT_FAILED,
  PAYMENT_CANCELLED,
  BALANCE_CHANGED
}
